# Generated by Django 6.0.3 on 2026-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_book_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Enter the book's natural language (e.g. English, Farsi etc.)", max_length=200)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
    ]